### ISSUE TITLE
No Clafghan

### ISSUE THREAD

**Issue by Paidtowin** [fparma/issue-tracker#1]
Fix it.

**Comment by MoistBaguette** [comment]
Working as Intended.

**Comment by Mallow234** [comment]
If you're paid to win then you probably aren't gettingh paid until cuel changes his mind

**Comment by elitehakor** [comment]
I second this issue

**Comment by Cuel** [comment]
AO is mostly the northern area, about 15% of the map. I don't see how that warrants the >1GB size
the rest of the map is only useful for convoys

there's also issues with the custom trees
https://files.catbox.moe/2u7sqm.jpg
https://files.catbox.moe/h25mas.jpg
