### ISSUE TITLE
Missing RHS Magazine

### ISSUE THREAD

**Issue by Saiatu** [fparma/issue-tracker#2]
No Entry 'bin\config.bin/Cfg.magazines.rhs_mag_an_m14_th3'. This came up after I updated CUP manually and downloaded the rest of the update files through Swifty.

**Comment by Saiatu** [comment]
When I load the editor or launch a scenario, too.

**Comment by Cuel** [comment]
I'm not getting that. It might be one of your missions
e.g I'm getting `No description fata.description` because I have an old mission on fata

**Comment by Saiatu** [comment]
I don't have any RHS equipment in this mission. Maybe I have to update the mission template?

**Comment by Saiatu** [comment]
Tested it again, and it is mission specific. I'll try updating the template and see if that fixes anything.
